batch_size: 32
Optimizer:
  learning_rate: 0.1
LR_Scheduler:
  step_size: 1
  gamma: 0.1
Logging:
  write_file: True
  write_tb: True
Misc:
  num_iterations: 1870
  val_freq: 1000
  checkpoint_freq: 1000
  copy_code: True
  n_gpu: 1
  eval_after_training: True
  validation_split: test

